---

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      image:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.0
