---

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  tessdata_version: "4.1.0"
  tessdata_path: "~/cache/tessdata"

jobs:
  dotnet:
    runs-on: ${{ inputs.os }}
    steps:
    - name: checkout
      uses: actions/checkout@v2.4.0
    - name: setup .NET
      # NOTE(rkm 2022-02-20) Uses global.json
      uses: actions/setup-dotnet@v1
    - name: cache tessdata
      id: cache-tessdata
      uses: actions/cache@v2.1.7
      with:
        path: ${{ env.tessdata_path }}
        key: 'tessdata|${{ env.tessdata_version }}|v3'
    - name: download tessdata
      if: steps.cache-tessdata.outputs.cache-hit != 'true'
      run: |
        set -euxo pipefail
        mkdir -p "${{ env.tessdata_path }}"
        curl \
            --location --silent \
            https://github.com/tesseract-ocr/tessdata/raw/${{ env.tessdata_version }}/eng.traineddata \
            --output "${{ env.tessdata_path }}/eng.traineddata"
        ls -l
        ls -l ~
        ls -l ~/cache
        ls -l ~/cache/tessdata
        ls -l "${{ env.tessdata_path }}"
    - name: symlink tessdata
      run: |
        set -euxo pipefail
        cp \
            "${{ env.tessdata_path }}/eng.traineddata" \
            "./data/tessdata/eng.traineddata"
        ls -l ./data/tessdata/
    - name: debug
      run: ls -l ~/cache
