---

name: linux

on:
  push:
  pull_request:
  # testing
  workflow_dispatch:

# NOTE(rkm 2022-02-20) These are not passed-on to any called workflows
defaults:
  run:
    shell: bash

env:
  OS: linux
  IMAGE: ubuntu-20.04

jobs:
  dotnet:
    uses: ./.github/workflows/_dotnet_tests.yml
    with:
      os: $OS
      image: $IMAGE
  java:
    uses: ./.github/workflows/_java_tests.yml
    with:
      os: $OS
      image: $IMAGE
  python:
    uses: ./.github/workflows/_python_tests.yml
    with:
      os: $OS
      image: $IMAGE
  packaging:
    needs: [dotnet, java, python]
    uses: ./.github/workflows/_packaging.yml
    with:
      os: $OS
      image: $IMAGE
