---

name: linux

on:
  push:
  pull_request:
  # testing
  workflow_dispatch:

jobs:
  dotnet:
    uses: ./.github/workflows/_dotnet_tests.yml
    with:
      os: linux
      image: ubuntu-20.04
  java:
    uses: ./.github/workflows/_java_tests.yml
    with:
      os: linux
      image: ubuntu-20.04
  python:
    uses: ./.github/workflows/_python_tests.yml
    with:
      os: linux
      image: ubuntu-20.04
  packaging:
    needs: [dotnet, java, python]
    uses: ./.github/workflows/_packaging.yml
    with:
      os: linux
      image: ubuntu-20.04
