---

name: main

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
  # testing
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - windows-2022
    runs_on: ${{ matrix.os }}
    steps:
    - uses: ./.github/jobs/tests.yml

