---

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  dotnet:
    runs-on: ubuntu-latest
#     runs-on: ${{ inputs.os }}
    steps:
    - run: echo test
