---

name: tests

on:
  push:
  pull_request:
  # testing
  workflow_dispatch:

# NOTE(rkm 2022-02-20) These are not passed-on to any called workflows
defaults:
  run:
    shell: bash

jobs:
  linux:
    uses: ./.github/workflows/_tests.yml
    with:
      os: ubuntu-20.04
  win:
    uses: ./.github/workflows/_tests.yml
    with:
      os: windows-2022
