---

name: windows

on:
  push:
  pull_request:
  # testing
  workflow_dispatch:

# NOTE(rkm 2022-02-20) These are not passed-on to any called workflows
defaults:
  run:
    shell: bash

env:
  os: windows
  image: windows-2022

jobs:
  dotnet:
    uses: ./.github/workflows/_dotnet_tests.yml
    with:
      os: ${{ env.OS }}
      image: ${{ env.IMAGE }}
  java:
    uses: ./.github/workflows/_java_tests.yml
    with:
      os: ${{ env.OS }}
      image: ${{ env.IMAGE }}
  python:
    uses: ./.github/workflows/_python_tests.yml
    with:
      os: ${{ env.OS }}
      image: ${{ env.IMAGE }}
  packaging:
    needs: [dotnet, java, python]
    uses: ./.github/workflows/_packaging.yml
    with:
      os: ${{ env.OS }}
      image: ${{ env.IMAGE }}
