---

name: windows

on:
  push:
  pull_request:
  # testing
  workflow_dispatch:

jobs:
  dotnet:
    uses: ./.github/workflows/_dotnet_tests.yml
    with:
      os: windows
      image: windows-2022
  java:
    uses: ./.github/workflows/_java_tests.yml
    with:
      os: windows
      image: windows-2022
  python:
    uses: ./.github/workflows/_python_tests.yml
    with:
      os: windows
      image: windows-2022
  packaging:
    needs: [dotnet, java, python]
    uses: ./.github/workflows/_packaging.yml
    with:
      os: windows
      image: windows-2022
